FROM node:20-alpine AS dev
WORKDIR /app
RUN npm install -g dotenv-cli
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
ENV NODE_ENV=development
EXPOSE 1337
CMD ["npm", "run", "dev"]
