FROM node:20-alpine AS dev
WORKDIR /app
RUN apk add --no-cache openssl
RUN npm install -g dotenv-cli
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
ENV NODE_ENV=development
EXPOSE 5000
CMD ["npm", "run", "dev"]
