FROM node:20-alpine AS prod
WORKDIR /app
RUN apk add --no-cache openssl
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=prod /app/dist ./dist
COPY --from=prod /app/node_modules ./node_modules
COPY --from=prod /app/package.json ./package.json
EXPOSE 3000
CMD ["npm", "start"]
